name: MAIN deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - '.github/workflows/ci-main.yml'
      - 'tf/main/**'

concurrency: development_environment

jobs:
  run:
    name: Run
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOYMENT_DEVELOPMENT }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOYMENT_DEVELOPMENT }}
#      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION_DEPLOYMENT_DEVELOPMENT }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_CLONE_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
      - name: run vet
        run: |
          go vet ./...
      - name: run test
        run: |
          go test ./... -v
      - name: run statick check
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck -checks "all" ./...
      - name: Build artefact
        env:
          CGO_ENABLED: 0
          GOOS: "linux"
          GOARCH: "amd64"
        run: |
          cd lambda
          mkdir -p ../src
          go build -o ../src/main
#      - name: use terraform
#        uses: hashicorp/setup-terraform@v1
#      - name: initialisation
#        run: |
#          cd tf/main
#          terraform init
#      - name: plan
#        run: |
#          cd tf/main
#          terraform plan -no-color -var-file main.tfvars -out=out.tfplan
#          terraform output
#      - name: apply
#        run: |
#          cd tf/main
#          terraform apply "out.tfplan"
